-- CREATE TABLE permissions (
--     permission CHARACTER VARYING PRIMARY KEY,
--     display CHARACTER VARYING
-- );

CREATE TABLE roles (
    role CHARACTER VARYING PRIMARY KEY,
    display CHARACTER VARYING
);

-- CREATE TABLE roles_permissions (
--     id SERIAL PRIMARY KEY,
--     role CHARACTER VARYING NOT NULL REFERENCES roles (role) ON DELETE CASCADE ON UPDATE CASCADE,
--     permission CHARACTER VARYING NOT NULL REFERENCES permissions (permission) ON DELETE CASCADE ON UPDATE CASCADE
-- );

CREATE TABLE users (
    username CHARACTER VARYING PRIMARY KEY,
    password_hash CHARACTER VARYING NOT NULL,
    role CHARACTER VARYING DEFAULT 'guest' NOT NULL REFERENCES roles (role) ON DELETE SET DEFAULT ON UPDATE CASCADE
);

CREATE TABLE sessions (
    sid UUID PRIMARY KEY,
    username CHARACTER VARYING NOT NULL REFERENCES users (username) ON DELETE CASCADE ON UPDATE CASCADE,
    last_updated timestamp with time zone NOT NULL,
    user_agent CHARACTER VARYING NOT NULL,
    refresh_tokens CHARACTER VARYING[] NOT NULL
);