CREATE TABLE files (
    hash CHARACTER VARYING(32) PRIMARY KEY,
    filename CHARACTER VARYING NOT NULL UNIQUE,
    owner CHARACTER VARYING REFERENCES users (username) ON DELETE SET NULL ON UPDATE CASCADE,
    description CHARACTER VARYING DEFAULT '',
    upload_time timestamp with time zone NOT NULL,
    size REAL NOT NULL
);

CREATE TABLE categories (
    category CHARACTER VARYING PRIMARY KEY
);

CREATE TABLE tags (
    tag CHARACTER VARYING PRIMARY KEY,
    description CHARACTER VARYING DEFAULT '',
    category CHARACTER VARYING DEFAULT 'Common' REFERENCES categories (category) ON DELETE SET NULL ON UPDATE CASCADE
);

-- CREATE TABLE tags_dependencies (
--     id SERIAL PRIMARY KEY,
--     tag CHARACTER VARYING REFERENCES tags (tag) ON DELETE CASCADE ON UPDATE CASCADE,
--     parent CHARACTER VARYING REFERENCES tags (tag) ON DELETE CASCADE ON UPDATE CASCADE
-- );

CREATE TABLE files_tags (
    id SERIAL PRIMARY KEY,
    file_hash CHARACTER VARYING(32) REFERENCES files (hash) ON DELETE CASCADE ON UPDATE CASCADE,
    tag CHARACTER VARYING REFERENCES tags (tag) ON DELETE CASCADE ON UPDATE CASCADE
);