CREATE TABLE files (
    hash CHARACTER VARYING(32) PRIMARY KEY,
    filename CHARACTER VARYING NOT NULL UNIQUE,
    owner CHARACTER VARYING REFERENCES users (username) ON DELETE SET NULL ON UPDATE CASCADE,
    description CHARACTER VARYING DEFAULT '',
    upload_time timestamp with time zone NOT NULL,
    size REAL NOT NULL
);

CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    category CHARACTER VARYING NOT NULL UNIQUE,
);

CREATE TABLE tags (
    id SERIAL PRIMARY KEY,
    tag CHARACTER VARYING NOT NULL UNIQUE,
    category_id INTEGER DEFAULT 1 REFERENCES categories (id) ON DELETE SET DEFAULT ON UPDATE CASCADE
);

CREATE TABLE files_tags (
    id SERIAL PRIMARY KEY,
    file_hash CHARACTER VARYING(32) REFERENCES files (hash) ON DELETE CASCADE ON UPDATE CASCADE,
    tag_id INTEGER REFERENCES tags (id) ON DELETE CASCADE ON UPDATE CASCADE
);